pdf_to_txt_task:
  description: >
    Turn this pdf {file_path} into a txt file.
  expected_output: >
    The exact text from the pdf.
  agent: pdf_to_txt # this one

summary_task:
  description: >
    Read and analyze this research paper, then extract key insights 
    related to {topic} and summarize them in a structured and concise format.
  expected_output: >
    A well-organized summary covering the main points, key findings, and essential takeaways 
    from the research papers, formatted in markdown.
  agent: reader_summarizer
  context: 
    - pdf_to_txt_task
  

quote_extraction_task:
  description: >
    Identify and extract the most relevant and impactful quotes from research papers related to {topic}.
    Focus on quotes that clearly convey important findings or arguments.
  expected_output: >
    A list of 10-15 key quotes with proper attribution.
  agent: quote_finder
  context: 
    - pdf_to_txt_task

quote_rating_task:
  description: >
    Evaluate the relevance, clarity, and impact of the extracted quotes.
    Assign each quote a rating from 1 to 10 based on its usefulness, clarity, and credibility.
  expected_output: >
    A list of rated quotes, each with its respective score (1-10).
  context:
    - quote_extraction_task
  agent: quote_rater

final_quote_selection_task:
  description: >
    Curate and refine the best quotes by selecting only those rated 5 or higher.
    Organize them in descending order from the highest-rated to the lowest-rated.
  expected_output: >
    A finalized and structured list of the most relevant quotes, ranked from highest to lowest rating.
  context:
    - quote_rating_task
  agent: final_editor
