pdf_to_txt_task:
  description: >
    Extract and return all the text content from the PDF file located at {file_path}.
  expected_output: >
    A string containing the full extracted text from the PDF file. This should be a clean and accurate representation of the document content, with all readable text included.
  agent: pdf_to_txt

summary_task:
  description: >
    Summarize the content of the research paper that was extracted in the previous task.
    Focus on key insights, main arguments, and findings. Return it in structured markdown format.
  expected_output: >
    A well-organized summary covering the main points, key findings, and essential takeaways 
    from the research papers, formatted in markdown.
  context:
    - pdf_to_txt_task
  agent: reader_summarizer
  

quote_extraction_task:
  description: >
    Identify 10-15 impactful quotes from the research paper content extracted earlier.
    These quotes should highlight important findings or compelling arguments related to {topic}.

  expected_output: >
    A list of 10-15 key quotes with proper attribution.
  context:
    - pdf_to_txt_task
  agent: quote_finder

quote_rating_task:
  description: >
    Evaluate the relevance, clarity, and impact of the extracted quotes.
    Before each quote, assign a rating from 1 to 10 based on its usefulness, clarity, and credibility.
  expected_output: >
    A list of rated quotes, each with its respective score (1-10).
  context:
    - quote_extraction_task
  agent: quote_rater

final_quote_selection_task:
  description: >
    Curate and refine the best quotes by selecting only those rated 5 or higher.
    Organize them in descending order from the highest-rated to the lowest-rated.
  expected_output: >
    A finalized and structured list of the most relevant quotes, ranked from highest to lowest rating.
  context:
    - quote_rating_task
  agent: final_editor

chat_interface_task:
  description: >
    Now that the summary and quotes are complete, interact with the user and answer any questions they have about the research paper.
    Use the summary, key quotes, and paper content as context when answering.
  expected_output: >
    A dynamic conversation where the user can ask questions and receive helpful answers based on the research content.
  agent: chat_analyst
